<script setup lang="ts">
import {ref,onMounted} from 'vue';
import {parentApi} from '../api';import type {ContentItem} from '../domain';import {vocabularyImage} from '../assets/vocabulary';
const items=ref<ContentItem[]>([]);const text=ref('');const meaning=ref('');const assetKey=ref('');const error=ref('');const busy=ref(false);const feedback=ref('');const suggestion=ref('');const key=ref(sessionStorage.getItem('parentAccessKey')||'');
const assets=['','food.apple','food.banana','food.bread','tableware.cup','tableware.plate'];
function saveKey(){sessionStorage.setItem('parentAccessKey',key.value);refresh()}
async function run(task:()=>Promise<any>,success:string){busy.value=true;error.value='';try{await task();feedback.value=success;await refresh()}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function refresh(){try{items.value=await parentApi.list()}catch(e){error.value=(e as Error).message}}
async function create(){if(!text.value.trim())return;await run(async()=>{await parentApi.create({text:text.value,meaningCn:meaning.value,type:'WORD',assetKey:assetKey.value});text.value='';meaning.value='';assetKey.value='';suggestion.value=''},'草稿已保存')}
async function generate(){if(!text.value.trim())return;await run(async()=>{const result=await parentApi.suggest(text.value);meaning.value=result.meaningCn;assetKey.value=result.assetKey;suggestion.value=result.exampleSentence},'AI 建议已填写到草稿，尚未发布；请先人工检查')}
async function transition(item:ContentItem,action:'review'|'approve'){await run(()=>parentApi.transition(item.id,action),action==='review'?'已提交人工审核':'已人工批准')}
async function edit(item:ContentItem){await run(()=>parentApi.update(item.id,{text:item.text,meaningCn:item.meaningCn,type:item.type,assetKey:item.assetKey}),'已保存修改，审核状态重置')}
async function publish(){if(!confirm('将所有已批准词条发布为新的不可变版本，继续吗？'))return;await run(async()=>{const p=await parentApi.publish();feedback.value='发布成功 '+p.packageVersion+'，共 '+p.itemCount+' 条'},'发布成功')}
async function importCsv(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;const lines=(await f.text()).replace(/^\uFEFF/,'').split(/\r?\n/).slice(1);let n=0;await run(async()=>{for(const line of lines){const [word,meaningCn='']=line.split(',');if(word?.trim()){await parentApi.create({text:word.trim(),meaningCn:meaningCn.trim(),type:'WORD',assetKey:''});n++}}},'成功导入 '+n+' 条')}
onMounted(refresh);
</script>
<template><main class="parent"><header><h1>家长控制台</h1><router-link to="/kid">进入儿童 3D 厨房 →</router-link></header>
<section><h2>访问密钥</h2><p>服务端需要配置 PARENT_ACCESS_KEY。密钥只保存在当前浏览器会话。</p><input type="password" v-model="key" placeholder="家长管理密钥"/><button @click="saveKey">保存并连接</button></section>
<section><h2>添加学习内容</h2><div class="form"><input v-model="text" placeholder="英语单词，例如 apple"/><input v-model="meaning" placeholder="中文释义"/><select v-model="assetKey"><option v-for="k in assets" :key="k" :value="k">{{k||'未关联 3D 素材'}}</option></select><button :disabled="busy" @click="generate">AI 补全建议</button><button :disabled="busy" @click="create">保存草稿</button></div><p v-if="suggestion">示例句：{{suggestion}}</p><small>AI 输出不会自动加入词库或发布。没有配置模型时仍可手工录入。</small></section>
<section><h2>CSV 导入（简单格式）</h2><input type="file" accept=".csv" @change="importCsv"/><small>表头 text,meaningCn。暂不支持带引号的逗号字段。</small></section>
<section><h2>审核与发布</h2><p>流程：DRAFT → REVIEW → READY → 发布独立快照。</p><div v-for="item in items" :key="item.id" class="item"><img v-if="vocabularyImage(item.assetKey)" :src="vocabularyImage(item.assetKey)" :alt="item.text" class="vocab-preview"/><input v-model="item.text" :disabled="item.status==='READY'"/><input v-model="item.meaningCn" :disabled="item.status==='READY'"/><select v-model="item.assetKey" :disabled="item.status==='READY'"><option v-for="k in assets" :key="k" :value="k">{{k||'未关联素材'}}</option></select><b>{{item.status}}</b><button v-if="item.status!=='READY'" :disabled="busy" @click="edit(item)">保存</button><button v-if="item.status==='DRAFT'" :disabled="busy" @click="transition(item,'review')">送审</button><button v-if="item.status==='REVIEW'" :disabled="busy" @click="transition(item,'approve')">人工批准</button></div><button :disabled="busy||!items.some(x=>x.status==='READY')" @click="publish">发布新的学习包版本</button></section>
<p class="error" role="alert">{{error}}</p><p class="success" role="status">{{feedback}}</p></main></template>
<style scoped>.parent{max-width:1050px;margin:auto;padding:18px;color:#41362b}header{display:flex;justify-content:space-between;align-items:center}.parent section{background:white;border-radius:14px;padding:20px;margin:16px 0}.form,.item{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.item{padding:12px 0;border-bottom:1px solid #ddd}.parent input,.parent select{padding:11px;border:1px solid #ddd;border-radius:8px;min-width:120px}.parent button{padding:11px 15px;background:#f4c178;border:0;border-radius:8px;cursor:pointer}.parent button:disabled{opacity:.5}.parent small{display:block;margin:8px 0;color:#766}.error{color:#b02}.success{color:#176a38} .vocab-preview{height:68px;width:68px;object-fit:contain;border-radius:12px;background:#f1f6ee;border:1px solid #e7efe5;flex-shrink:0}</style>