<script setup lang="ts">
import {ref,onMounted,onBeforeUnmount} from 'vue';import {KitchenScene} from '../game/KitchenScene';import {starterItems,type ContentItem,type AttemptEvent} from '../domain';import {queueAttempt,syncAttempts} from '../offline/db';import {nextHint,type HintLevel} from '../game/rules';import {latestPackage} from '../api';import {db} from '../offline/db';
const container=ref<HTMLElement>();const targets=ref<ContentItem[]>(starterItems);const index=ref(0);const hint=ref<HintLevel>(0);const errors=ref(0);const message=ref('听一听，找到正确的物品');const finished=ref(false);const sessionId=crypto.randomUUID();let packageVersion='starter-1';let started=performance.now();let kitchen:KitchenScene|undefined;
const current=()=>targets.value[index.value];
function speak(){const item=current();if(!item)return;speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(item.text);utterance.lang='en-US';utterance.rate=.8;speechSynthesis.speak(utterance)}
function help(){hint.value=nextHint(hint.value);if(hint.value>=4)message.value='提示：'+current().meaningCn;else if(hint.value>=2)message.value='看看这些物品，再试一次';speak()}
async function select(key:string){if(finished.value)return;const item=current();if(key!==item.assetKey){errors.value++;hint.value=nextHint(hint.value);message.value='再听一次，试试看';speak();return}
 const event:AttemptEvent={eventId:crypto.randomUUID(),sessionId,contentItemId:item.id,packageVersion,activityVersion:1,firstTryCorrect:errors.value===0,hintLevel:hint.value,semanticErrors:errors.value,responseMs:Math.round(performance.now()-started),occurredAt:new Date().toISOString(),syncStatus:'PENDING'};
 await queueAttempt(event);message.value='答对啦！';if(index.value===targets.value.length-1){finished.value=true;syncAttempts(localStorage.getItem('kidToken')??'').catch(()=>{});return}index.value++;hint.value=0;errors.value=0;started=performance.now();setTimeout(speak,300)}
onMounted(async()=>{try{const pkg=await latestPackage();await db.packages.put(pkg);const usable=pkg.items.filter(x=>starterItems.some(y=>y.assetKey===x.assetKey));if(usable.length){targets.value=usable;packageVersion=pkg.packageVersion}}catch{const cached=await db.packages.orderBy('publishedAt').last();if(cached){const usable=cached.items.filter(x=>starterItems.some(y=>y.assetKey===x.assetKey));if(usable.length){targets.value=usable;packageVersion=cached.packageVersion}}}}if(container.value){kitchen=new KitchenScene(container.value,targets.value);kitchen.onSelect=select}window.addEventListener('online',syncNow);document.addEventListener('visibilitychange',visible)});
onBeforeUnmount(()=>{kitchen?.dispose();speechSynthesis.cancel();window.removeEventListener('online',syncNow);document.removeEventListener('visibilitychange',visible)});
function syncNow(){syncAttempts(localStorage.getItem('kidToken')??'').catch(()=>{})}function visible(){if(!document.hidden)syncNow()}
</script>
<template><main class="kid"><header><h1>🍎 英语小厨房</h1><span>{{Math.min(index+1,targets.length)}} / {{targets.length}}</span></header><div class="task"><p>{{finished?'今天的任务完成啦！🎉':message}}</p><strong v-if="!finished">{{current().text}}</strong></div><div ref="container" class="scene" role="application" aria-label="3D 厨房物品选择区"></div><div class="actions" v-if="!finished"><button @click="speak">🔊 再听一遍</button><button @click="help">💡 给我提示</button></div><div v-else class="actions"><button @click="location.reload()">再玩一次</button></div><small>当前使用浏览器朗读，正式发布需要预生成英语音频。</small></main></template>
<style scoped>.kid{max-width:980px;margin:auto;padding:16px;color:#564126}header{display:flex;justify-content:space-between;align-items:center}.task{text-align:center;background:#fff7e7;border-radius:22px;padding:14px;margin:8px 0}.task p{font-size:20px}.task strong{font-size:30px;color:#9a623b}.scene{height:min(53vh,450px);border-radius:24px;overflow:hidden;background:#f3dfb9}.actions{display:flex;gap:16px;justify-content:center;margin:16px}.actions button{border:0;border-radius:20px;padding:18px 25px;background:#e8a254;color:#34250e;font-size:19px;min-height:58px}.kid small{display:block;text-align:center;color:#8b806f}@media(max-width:500px){.actions{flex-direction:column}.scene{height:45vh}}</style>