<script setup lang="ts">
import {computed,onMounted,ref} from 'vue';
import {useRouter} from 'vue-router';
import {loadKitchenProgress} from '../game/kitchenWorld';
import {loadThemeProgress,themeWorlds} from '../game/worldCatalog';
const router=useRouter();const refresh=ref(0);
onMounted(()=>refresh.value++);
const kitchen=computed(()=>{refresh.value;return loadKitchenProgress()});
const worlds=computed(()=>[
 {id:'kitchen-world',route:'/kid/world/kitchen',order:1,icon:'🍳',code:'WORLD 1',title:'魔法厨房',description:'在 3D 厨房里认识食物与餐具。',completed:kitchen.value.completed,unlocked:true},
 ...themeWorlds.map((w,i)=>{refresh.value;const p=loadThemeProgress(w.id);const previous=i===0?kitchen.value.completed:loadThemeProgress(themeWorlds[i-1].id).completed;return{id:w.id,route:'/kid/world/'+w.id,order:w.order,icon:w.icon,code:w.code,title:w.title,description:w.description,completed:p.completed,unlocked:previous}})
]);
function enter(w:any){if(w.unlocked)router.push(w.route)}
</script>
<template><main class="map-page"><div class="wrap"><header><div><span>LITTLE EXPLORERS</span><h1>🌍 奇妙英语世界</h1><p>每个世界都是一个完整主题：先认识，再辨认、配对、听指令，最后完成挑战。</p></div><router-link to="/parent">家长中心</router-link></header>
<section class="journey"><div class="path"></div><button v-for="w in worlds" :key="w.id" class="world" :class="{locked:!w.unlocked,done:w.completed}" :disabled="!w.unlocked" @click="enter(w)"><div class="planet">{{w.unlocked?w.icon:'🔒'}}</div><div class="world-copy"><small>{{w.code}}</small><h2>{{w.title}}</h2><p>{{w.description}}</p><strong v-if="w.completed">✅ 已完成 · 可以再次探索</strong><strong v-else-if="w.unlocked">▶ 进入世界</strong><strong v-else>完成上一个世界后解锁</strong></div></button></section>
<div class="coming"><span>🚗</span><b>更多世界逐步开放</b><p>超市、交通、公园、生日派对等主题会继续复用同一学习闭环。</p></div></div></main></template>
<style scoped>
.map-page{min-height:100vh;background:radial-gradient(circle at 10% 10%,#fff0cf,transparent 30%),radial-gradient(circle at 90% 8%,#d7f4f0,transparent 30%),#f3f7ff;color:#394b68;font-family:system-ui,"Microsoft YaHei",sans-serif}.wrap{max-width:1040px;margin:auto;padding:28px 24px 70px}header{display:flex;justify-content:space-between;gap:20px;align-items:center;background:linear-gradient(120deg,#7962d8,#9d8beb);color:#fff;padding:30px 34px;border-radius:30px;box-shadow:0 13px 0 #d9d7ef}header span{font-size:11px;letter-spacing:2px;font-weight:900;opacity:.82}header h1{font-size:32px;margin:6px 0}header p{margin:0;max-width:670px;line-height:1.7;opacity:.9}header a{background:#fff;color:#6754bd;text-decoration:none;padding:12px 16px;border-radius:15px;font-weight:850;white-space:nowrap}.journey{position:relative;display:grid;gap:17px;margin-top:34px}.path{position:absolute;left:47px;top:40px;bottom:40px;width:8px;background:linear-gradient(#f7c75e,#8bd6bd,#9d8de7);border-radius:9px}.world{position:relative;display:flex;align-items:center;gap:24px;text-align:left;border:0;background:#fff;border-radius:26px;padding:22px 28px;box-shadow:0 8px 0 #dfe4f3;cursor:pointer;color:inherit}.planet{position:relative;z-index:1;width:64px;height:64px;display:grid;place-items:center;border-radius:50%;background:#fff4cf;font-size:35px;border:5px solid #fff;box-shadow:0 4px 12px #8a8aa433}.world-copy{flex:1}.world-copy small{color:#9789cd;font-weight:900;letter-spacing:1.3px}.world-copy h2{margin:3px 0;font-size:24px;color:#5c4ca4}.world-copy p{margin:3px 0 8px;color:#7b8495}.world-copy strong{font-size:13px;color:#4a9a77}.world.locked{opacity:.55;cursor:not-allowed;filter:grayscale(.55)}.world.done{box-shadow:0 8px 0 #bfe8d4}.coming{margin-top:26px;text-align:center;background:#fff;border-radius:22px;padding:18px;color:#7d8494}.coming span{font-size:30px}.coming b{display:block;color:#6356a1}.coming p{margin:5px}@media(max-width:650px){.wrap{padding:14px 12px 50px}header{padding:22px;align-items:flex-start;flex-direction:column}header h1{font-size:25px}.world{padding:16px;gap:14px}.planet{width:52px;height:52px;font-size:29px}.path{left:38px}.world-copy h2{font-size:20px}}</style>
