<script setup lang="ts">
import {computed,onMounted,ref} from 'vue';
import {useRouter} from 'vue-router';
import {latestPackage} from '../api';
import {loadKitchenProgress} from '../game/kitchenWorld';
import {loadThemeProgress,themeWorlds} from '../game/worldCatalog';
const router=useRouter();const refresh=ref(0);const vocabularyCount=ref(0);
onMounted(async()=>{refresh.value++;try{const p=await latestPackage();vocabularyCount.value=p.items.filter(x=>x.status==='READY').length}catch{}});
const kitchen=computed(()=>{refresh.value;return loadKitchenProgress()});
const worlds=computed(()=>[
 {id:'kitchen-world',route:'/kid/world/kitchen',order:1,icon:'🍳',scene:'/scenes/kitchen-world.svg',code:'WORLD 1',title:'魔法厨房',description:'在 3D 厨房里认识食物与餐具。',completed:kitchen.value.completed,unlocked:true},
 ...themeWorlds.map((w,i)=>{refresh.value;const p=loadThemeProgress(w.id);const previous=i===0?kitchen.value.completed:loadThemeProgress(themeWorlds[i-1].id).completed;return{id:w.id,route:'/kid/world/'+w.id,order:w.order,icon:w.icon,scene:w.scene,code:w.code,title:w.title,description:w.description,completed:p.completed,unlocked:previous}})
]);
function enter(w:any){if(w.unlocked)router.push(w.route)}
</script>
<template><main class="map-page"><div class="wrap"><header><div><span>LITTLE EXPLORERS</span><h1>🌍 奇妙英语世界</h1><p>主题世界负责沉浸式学习；词库学习馆负责覆盖全部已发布单词，两条路径互相补充。</p></div><router-link to="/parent">家长中心</router-link></header>
<section class="vocab-entry" @click="router.push('/kid/vocabulary')"><img src="/scenes/vocabulary-library.svg" alt="词库学习馆"/><div><small>ALL PUBLISHED WORDS</small><h2>📚 词库学习馆</h2><p>不再局限于固定场景。{{vocabularyCount||'全部'}} 个已发布词汇按 10 词/单元自动编排，可搜索任意单词直接学习。</p><strong>进入词库学习 →</strong></div><span class="count">{{vocabularyCount||'—'}}</span></section>
<section class="journey"><div class="path"></div><button v-for="w in worlds" :key="w.id" class="world" :class="{locked:!w.unlocked,done:w.completed}" :disabled="!w.unlocked" @click="enter(w)"><img class="world-scene" :src="w.scene" :alt="w.title"/><div class="world-copy"><small>{{w.code}}</small><h2>{{w.icon}} {{w.title}}</h2><p>{{w.description}}</p><strong v-if="w.completed">✅ 已完成 · 可以再次探索</strong><strong v-else-if="w.unlocked">▶ 进入世界</strong><strong v-else>完成上一个世界后解锁</strong></div></button></section>
<div class="coming"><b>主题世界 ≠ 全部词库</b><p>场景世界用于高质量主题学习；没有专属场景的词也会自动进入词库学习馆，不会再“导入后无处可学”。</p></div></div></main></template>
<style scoped>
.map-page{min-height:100vh;background:radial-gradient(circle at 10% 10%,#fff0cf,transparent 30%),radial-gradient(circle at 90% 8%,#d7f4f0,transparent 30%),#f3f7ff;color:#394b68;font-family:system-ui,"Microsoft YaHei",sans-serif}.wrap{max-width:1080px;margin:auto;padding:28px 24px 70px}header{display:flex;justify-content:space-between;gap:20px;align-items:center;background:linear-gradient(120deg,#7962d8,#9d8beb);color:#fff;padding:30px 34px;border-radius:30px;box-shadow:0 13px 0 #d9d7ef}header span{font-size:11px;letter-spacing:2px;font-weight:900;opacity:.82}header h1{font-size:32px;margin:6px 0}header p{margin:0;max-width:720px;line-height:1.7;opacity:.9}header a{background:#fff;color:#6754bd;text-decoration:none;padding:12px 16px;border-radius:15px;font-weight:850;white-space:nowrap}.vocab-entry{position:relative;display:grid;grid-template-columns:300px 1fr;gap:24px;align-items:center;background:#fff;margin:24px 0;border-radius:28px;padding:16px;box-shadow:0 9px 0 #dfe3f0;cursor:pointer;overflow:hidden}.vocab-entry img{width:100%;border-radius:21px}.vocab-entry small{color:#947fce;font-weight:900;letter-spacing:1.3px}.vocab-entry h2{font-size:28px;color:#5c4ca5;margin:5px 0}.vocab-entry p{color:#747d8e;line-height:1.6}.vocab-entry strong{color:#4a9c78}.count{position:absolute;right:22px;top:18px;background:#f0ecff;color:#745fc2;border-radius:999px;padding:8px 12px;font-weight:950}.journey{display:grid;grid-template-columns:1fr 1fr;gap:18px}.path{display:none}.world{display:grid;grid-template-columns:190px 1fr;align-items:center;gap:17px;text-align:left;border:0;background:#fff;border-radius:26px;padding:13px;box-shadow:0 8px 0 #dfe4f3;cursor:pointer;color:inherit;overflow:hidden}.world-scene{width:190px;height:125px;object-fit:cover;border-radius:19px}.world-copy small{color:#9789cd;font-weight:900;letter-spacing:1.3px}.world-copy h2{margin:3px 0;font-size:22px;color:#5c4ca4}.world-copy p{margin:3px 0 8px;color:#7b8495;font-size:12px}.world-copy strong{font-size:12px;color:#4a9a77}.world.locked{opacity:.55;cursor:not-allowed;filter:grayscale(.45)}.world.done{box-shadow:0 8px 0 #bfe8d4}.coming{margin-top:26px;text-align:center;background:#fff;border-radius:22px;padding:18px;color:#7d8494}.coming b{display:block;color:#6356a1}.coming p{margin:5px}@media(max-width:800px){.journey{grid-template-columns:1fr}.vocab-entry{grid-template-columns:220px 1fr}.world{grid-template-columns:160px 1fr}.world-scene{width:160px}}@media(max-width:650px){.wrap{padding:14px 12px 50px}header{padding:22px;align-items:flex-start;flex-direction:column}header h1{font-size:25px}.vocab-entry{grid-template-columns:1fr}.vocab-entry img{max-height:190px;object-fit:cover}.world{grid-template-columns:120px 1fr}.world-scene{width:120px;height:105px}.world-copy h2{font-size:19px}.count{top:10px;right:10px}}</style>
